### ISSUE TITLE
Missing Permissions during GitHub Actions

### ISSUE THREAD

**Issue by vbabiy** [apppackio/build-action#1]
When using GitHub Actions I had to add the following permission to the IAM policy: 

- `codebuild:StartBuild`
- `codebuild:BatchGetProjects`

```
      {
        "Action": [
          "codebuild:BatchGetProjects",
          "codebuild:StartBuild"

        ],
        "Effect": "Allow",
        "Resource": "****",
        "Sid": "Projects"
      },
```

**Comment by ipmb** [comment]
Fixed in https://github.com/apppackio/apppack-backend/commit/6176e30963259da628c52a0b9b8f512ee7c77580
